--COUNT_OF_CCR_ORDERS VIEW
CREATE OR REPLACE FORCE EDITIONABLE VIEW "COUNT_OF_CCR_ORDERS" ("YEAR", "TOTAL_COMPLETE_ORDERS", "TOTAL_CANCELLED_ORDERS", "TOTAL_REFUNDED_ORDERS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    EXTRACT(YEAR FROM o.ORDER_DATE) AS year,
    COUNT(CASE WHEN o.ORDER_STATUS = 'Complete' THEN 1 END) AS total_complete_orders,
    COUNT(CASE WHEN o.ORDER_STATUS = 'Canceled' THEN 1 END) AS total_cancelled_orders,
    COUNT(CASE WHEN o.ORDER_STATUS = 'Refunded' THEN 1 END) AS total_refunded_orders
FROM
    OLIST_ORDERS o
GROUP BY
    EXTRACT(YEAR FROM o.ORDER_DATE)
ORDER BY
    year;