--CUSTOMER_PURCHASE_SUMMARY
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CUSTOMER_PURCHASE_SUMMARY" ("CUSTOMER_ID", "FULL_NAME", "EMAIL_ADDRESS", "TOTAL_PRODUCTS_PURCHASED", "TOTAL_AMOUNT_SPENT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    c.CUSTOMER_ID,
    c.FULL_NAME,
    c.email_address,
    COUNT(DISTINCT oi.PRODUCT_ID) AS total_products_purchased,
    SUM(oi.QUANTITY * p.UNIT_PRICE) AS total_amount_spent
FROM
    OLIST_CUSTOMERS c
JOIN
    OLIST_ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
JOIN
    OLIST_ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN
    OLIST_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    c.CUSTOMER_ID, c.FULL_NAME,c.email_Address
ORDER BY
    total_amount_spent DESC;