 --CUSTOMER_ORDER_PRODUCT_DETAILS_VIEW
 CREATE OR REPLACE FORCE EDITIONABLE VIEW "CUSTOMER_ORDER_PRODUCT_DETAILS_VIEW" ("CUSTOMER_ID", "ORDER_ID", "STORE_ID", "STORE_NAME", "FULL_NAME", "EMAIL_ADDRESS", "ORDER_DATE", "ORDER_STATUS", "PRODUCT_NAME", "UNIT_PRICE", "QUANTITY", "TOTAL_AMOUNT_PAID", "PAYMENT_TYPE", "REVIEW_MESSAGE", "RATING") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    c.CUSTOMER_ID,
    o.ORDER_ID,
    s.STORE_ID,
    s.STORE_NAME,
    c.FULL_NAME,
    c.EMAIL_ADDRESS,
    o.ORDER_DATE,
    o.ORDER_STATUS,
    p.PRODUCT_NAME,
    p.UNIT_PRICE,
    oi.QUANTITY,
    (oi.QUANTITY * p.UNIT_PRICE) AS total_amount_paid,
    op.PAYMENT_TYPE,
    r.REVIEW_MESSAGE,
    r.RATING
FROM
    OLIST_CUSTOMERS c
JOIN
    OLIST_ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
JOIN
    OLIST_STORES s ON o.STORE_ID = s.STORE_ID
JOIN
    OLIST_ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN
    OLIST_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
JOIN
    OLIST_ORDER_PAYMENTS op ON o.ORDER_ID = op.ORDER_ID
LEFT JOIN
    OLIST_ORDER_REVIEWS r ON o.ORDER_ID = r.ORDER_ID
ORDER BY
    c.CUSTOMER_ID, o.ORDER_ID;