--DAILY_SALES_SUMMARY_VIEW
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DAILY_SALES_SUMMARY_VIEW" ("ORDER_DATE", "DAILY_SALES") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    TRUNC(o.ORDER_DATE) AS order_date,
    SUM(oi.QUANTITY * p.UNIT_PRICE) AS daily_sales
FROM
    OLIST_ORDERS o
JOIN
    OLIST_ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN
    OLIST_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    TRUNC(o.ORDER_DATE)
ORDER BY
    TRUNC(o.ORDER_DATE) desc;