--MONTHLY_SALES_TRENDS_BY_YEAR
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "MONTHLY_SALES_TRENDS_BY_YEAR" ("YEAR", "MONTH_NAME", "TOTAL_SALES") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    EXTRACT(YEAR FROM o.ORDER_DATE) AS year,
    TO_CHAR(o.ORDER_DATE, 'Month-YYYY') AS month_name,
    SUM(oi.QUANTITY * p.UNIT_PRICE) AS total_sales
FROM OLIST_ORDERS o
JOIN OLIST_ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN OLIST_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY EXTRACT(YEAR FROM o.ORDER_DATE), TO_CHAR(o.ORDER_DATE, 'Month-YYYY'), EXTRACT(MONTH FROM o.ORDER_DATE)
ORDER BY EXTRACT(YEAR FROM o.ORDER_DATE), EXTRACT(MONTH FROM o.ORDER_DATE);