--NO_OF_ITEMS_IN_EACH_CATEGORY VIEW
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NO_OF_ITEMS_IN_EACH_CATEGORY" ("CATEGORY", "TOTAL_ITEMS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    p.CATEGORY,
    SUM(oi.QUANTITY) AS total_items
FROM
    OLIST_PRODUCTS p
JOIN
    OLIST_ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID
GROUP BY
    p.CATEGORY;