--SALES_GROWTH_OR_DECLINE VIEW
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SALES_GROWTH_OR_DECLINE" ("YEAR", "CATEGORY", "TOTAL_SALES") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    EXTRACT(YEAR FROM o.ORDER_DATE) AS year,
    p.CATEGORY,
    SUM(oi.QUANTITY * p.UNIT_PRICE) AS total_sales
FROM
    OLIST_ORDERS o
JOIN
    OLIST_ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN
    OLIST_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    EXTRACT(YEAR FROM o.ORDER_DATE), p.CATEGORY
ORDER BY
    year, p.CATEGORY;