--TOTAL_NO_OF_ORDERS_PER_YEAR VIEW
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TOTAL_NO_OF_ORDERS_PER_YEAR" ("ORDER_COUNT", "ORDER_YEAR") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT COUNT(*) AS ORDER_COUNT, TO_CHAR(ORDER_DATE, 'YYYY') AS ORDER_YEAR
FROM OLIST_ORDERS
GROUP BY TO_CHAR(ORDER_DATE, 'YYYY')
ORDER BY ORDER_YEAR;