--TOTAL_AVAILABLE_RECORDS_IN_EACH_TABLE VIEW
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TOTAL_AVAILABLE_RECORDS_IN_EACH_TABLE" ("CUSTOMERS", "CUSTOMER_COUNT", "ORDERS", "ORDER_COUNT", "PRODUCTS", "PRODUCT_COUNT", "STORES", "STORE_COUNT", "PAYMENTS", "PAYMENT_COUNT", "REVIEWS", "REVIEW_COUNT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    'Customers' as Customers, (SELECT COUNT(*) FROM OLIST_CUSTOMERS) AS customer_count,
    'Orders' as Orders, (SELECT COUNT(*) FROM OLIST_ORDERS) AS order_count,
    'Products' as Products, (SELECT COUNT(*) FROM OLIST_PRODUCTS) AS product_count,
    'Stores' as Stores, (SELECT COUNT(*) FROM OLIST_STORES) AS store_count,
    'Payments' as Payments, (SELECT COUNT(*) FROM OLIST_ORDER_PAYMENTS) as Payment_count,
    'Reviews' as Reviews, (SELECT COUNT(*) FROM OLIST_ORDER_REVIEWS) as Review_Count
FROM
    dual;